apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  source:
    path: manifests/apps/demo-app
    repoURL: https://github.com/BoraKostem/demo-app-ArgoCD.git
    targetRevision: HEAD
  project: argocd-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true